[package]
name = "wechat-send-guard-platform-macos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "macOS-specific platform adapter for WeChatSendGuard."
build = "build.rs"

[dependencies]
serde_json.workspace = true
uuid.workspace = true
wechat-send-guard-core = { path = "../guard-core" }
wechat-send-guard-platform-api = { path = "../platform-api" }

[build-dependencies]
cc = "1.4.4"
