<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WeChatSendGuard.Core\WeChatSendGuard.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>WeChatSendGuard</AssemblyName>
    <RootNamespace>WeChatSendGuard.App</RootNamespace>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
